repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: local
  hooks:
    - id: ruff
      name: ruff (linter)
      entry: poetry run ruff check --fix
      language: system
      types: [python]

    - id: black
      name: black (code formatter)
      entry: poetry run black
      language: system
      types: [python]

    - id: isort-fix
      name: isort (import sorting & fixing)
      entry: poetry run isort --settings-path=.isort.cfg .
      language: system
      types: [python]

    - id: isort-check
      name: isort (import validation)
      entry: poetry run isort --check-only --diff --settings-path=.isort.cfg .
      language: system
      types: [python]
