repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: local
  hooks:
    - id: ruff
      name: ruff (linter)
      entry: poetry run ruff check --fix
      language: system
      types: [python]

    - id: black
      name: black (code formatter)
      entry: poetry run black
      language: system
      types: [python]

    # Only run check, don't auto-fix imports
    - id: isort-check
      name: isort (import validation)
      entry: poetry run isort --check-only --diff --profile black --line-length 120 .
      language: system
      types: [python]
      # Allow this hook to fail and show errors
      verbose: true

    # Only run after checking, to provide a way to fix issues
    - id: isort-fix
      name: isort (import sorting & fixing)
      entry: poetry run isort --profile black --line-length 120 .
      language: system
      types: [python]
      stages: [manual]
