repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: local
  hooks:
    - id: ruff
      name: ruff (linter)
      entry: poetry run ruff check --fix
      language: system
      types: [python]

    - id: black
      name: black (code formatter)
      entry: poetry run black
      language: system
      types: [python]

    - id: isort
      name: isort (import sorting)
      entry: poetry run isort
      language: system
      types: [python]

# Ensure pyproject.toml has:
# [tool.isort]
# profile = "black"
#
# [tool.black]
# line-length = 88 # Or your preferred line length
# # other black configurations
#
# [tool.ruff]
# line-length = 88 # Match black's line length
# select = ["E", "F", "W", "I", "UP", "PL", "Q"] # Example - customize as needed
# # You can add more Ruff configurations here
# # e.g., ignore specific rules:
# # ignore = ["E501"]
# # extend-select = ["C90"] # for McCabe complexity if desired
