version: "3.8"

services:
  proxy-service:
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./app:/app/app
      - ./wallets:/app/app/wallets
      - ./request_logs:/app/request_logs
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - proxy-network

  gpu-container:
    build:
      context: ../gpu_container
      dockerfile: Dockerfile
    environment:
      - MODEL_ID=WhereIsAI/UAE-Large-V1
      - VLLM_MODEL_ID=mrfakename/mistral-small-3.1-24b-instruct-2503-hf
      - VLLM_GPU_UTILIZATION=0.8
    volumes:
      - gpu-container-data:/artifacts
      - ../gpu_container:/gpu_container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - proxy-network

volumes:
  gpu-container-data:

networks:
  proxy-network:
    driver: bridge
